# Generated by Django 4.2.30 on 2026-06-23 01:52

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Household",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("household_head_name", models.CharField(max_length=255)),
                ("tole", models.CharField(blank=True, max_length=255)),
                (
                    "wealth_class",
                    models.CharField(choices=[("rich", "Rich"), ("medium", "Medium"), ("poor", "Poor")], max_length=16),
                ),
                ("population_male", models.PositiveIntegerField(default=0)),
                ("population_female", models.PositiveIntegerField(default=0)),
                ("livestock_cattle", models.PositiveIntegerField(default=0)),
                ("livestock_buffalo", models.PositiveIntegerField(default=0)),
                ("livestock_goat", models.PositiveIntegerField(default=0)),
                (
                    "education_level",
                    models.CharField(
                        blank=True,
                        choices=[("illiterate", "Illiterate"), ("basic", "Basic"), ("secondary_plus", "Secondary+")],
                        max_length=16,
                    ),
                ),
                ("occupation", models.CharField(blank=True, max_length=255)),
                ("caste_ethnicity", models.CharField(blank=True, max_length=255)),
                ("registration_date", models.DateField()),
                (
                    "entry_fee_type",
                    models.CharField(
                        choices=[("new_household", "New household"), ("split_household", "Split household")],
                        default="new_household",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")], default="active", max_length=16
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Household",
                "verbose_name_plural": "Households",
                "ordering": ["household_head_name"],
            },
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("full_name", models.CharField(max_length=255)),
                ("citizenship_no", models.CharField(db_index=True, max_length=64, unique=True)),
                (
                    "membership_type",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("lifetime", "Lifetime"),
                            ("institutional", "Institutional"),
                            ("special", "Special"),
                            ("other", "Other"),
                        ],
                        default="general",
                        max_length=16,
                    ),
                ),
                (
                    "membership_status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive"), ("cancelled", "Cancelled")],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("date_joined", models.DateField()),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="members", to="members.household"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="member_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Member",
                "verbose_name_plural": "Members",
                "ordering": ["full_name"],
            },
        ),
        migrations.CreateModel(
            name="MembershipRenewal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fiscal_year", models.CharField(max_length=16)),
                (
                    "fee_tier",
                    models.CharField(
                        choices=[
                            ("on_time", "On time"),
                            ("overdue_3yr", "Overdue up to 3 years"),
                            ("overdue_5yr", "Overdue up to 5 years"),
                            ("overdue_5yr_plus", "Overdue more than 5 years"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "fee_charged",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                ("paid_date", models.DateField()),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="renewals", to="members.member"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Membership Renewal",
                "verbose_name_plural": "Membership Renewals",
                "ordering": ["-fiscal_year"],
            },
        ),
        migrations.AddConstraint(
            model_name="membershiprenewal",
            constraint=models.UniqueConstraint(fields=("member", "fiscal_year"), name="unique_member_fiscal_year"),
        ),
    ]
