# Generated by Django 4.2.30 on 2026-07-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='membership_photo',
            field=models.FileField(blank=True, null=True, upload_to='membership_photos/'),
        ),
    ]
