# Generated by Django 4.2.30 on 2026-07-08 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_membership_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='citizenship_no',
        ),
        migrations.RemoveField(
            model_name='member',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='member',
            name='membership_photo',
        ),
        migrations.RemoveField(
            model_name='member',
            name='membership_status',
        ),
        migrations.RemoveField(
            model_name='member',
            name='membership_type',
        ),
        migrations.AddField(
            model_name='household',
            name='citizenship_no',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='household',
            name='date_joined',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='household',
            name='membership_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('cancelled', 'Cancelled')], default='active', max_length=16),
        ),
        migrations.AddField(
            model_name='household',
            name='membership_type',
            field=models.CharField(choices=[('general', 'General'), ('lifetime', 'Lifetime'), ('institutional', 'Institutional'), ('special', 'Special'), ('other', 'Other')], default='general', max_length=16),
        ),
        migrations.AddField(
            model_name='household',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='household_head_photos/'),
        ),
    ]
