# Generated by Django 4.2.30 on 2026-07-08 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_remove_member_citizenship_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='member_photo',
            field=models.FileField(blank=True, null=True, upload_to='member_photos/'),
        ),
    ]
