# Generated by Django 4.2.30 on 2026-07-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_member_member_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='relation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
