# Generated by Django 4.2.30 on 2026-07-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_member_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='contact_number',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
