# Generated by Django 4.2.30 on 2026-07-09 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_household_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='membership_number',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
