# Generated by Django 4.2.30 on 2026-07-09 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_household_membership_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='citizenship_no',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
