# Generated by Django 4.2.30 on 2026-07-09 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_alter_household_citizenship_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='membership_number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
