# Generated by Django 4.2.30 on 2026-07-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_alter_household_membership_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='english_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
