# Generated by Django 4.2.30 on 2026-08-30 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_household_english_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='full_name_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
