# Generated by Django 4.2.30 on 2026-09-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_member_full_name_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
