# Generated by Django 4.2.30 on 2026-06-23 02:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("members", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommitteeMember",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("chair", "Chair"),
                            ("vice_chair", "Vice Chair"),
                            ("secretary", "Secretary"),
                            ("joint_secretary", "Joint Secretary"),
                            ("treasurer", "Treasurer"),
                            ("member", "Member"),
                        ],
                        max_length=20,
                    ),
                ),
                ("gender", models.CharField(max_length=16)),
                ("caste_ethnicity", models.CharField(blank=True, max_length=255)),
                ("term_start", models.DateField()),
                ("term_end", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("vacant", "Vacant"), ("removed", "Removed")],
                        default="active",
                        max_length=16,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="committee_roles", to="members.member"
                    ),
                ),
            ],
            options={
                "verbose_name": "Committee Member",
                "verbose_name_plural": "Committee Members",
                "ordering": ["-term_start", "position"],
            },
        ),
        migrations.CreateModel(
            name="SubCommittee",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("account_fund", "Account / Fund"),
                            ("dispute_resolution", "Dispute Resolution"),
                            ("infrastructure", "Infrastructure"),
                            ("monitoring", "Monitoring"),
                            ("livelihood", "Livelihood"),
                            ("anti_poaching", "Anti Poaching"),
                            ("fire_control", "Fire Control"),
                            ("youth_sports", "Youth / Sports"),
                            ("women", "Women"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("tor_description", models.TextField()),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sub-committee",
                "verbose_name_plural": "Sub-committees",
            },
        ),
        migrations.CreateModel(
            name="OathRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("oath_date", models.DateField()),
                (
                    "committee_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="oaths", to="governance.committeemember"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Oath Record",
                "verbose_name_plural": "Oath Records",
                "ordering": ["-oath_date"],
            },
        ),
        migrations.CreateModel(
            name="NoConfidenceMotion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "target_type",
                    models.CharField(
                        choices=[("full_committee", "Full Committee"), ("single_officer", "Single Officer")], max_length=16
                    ),
                ),
                ("signatures_count", models.PositiveIntegerField(default=0)),
                ("filed_date", models.DateField()),
                (
                    "assembly_decision",
                    models.CharField(
                        choices=[("pending", "Pending"), ("passed", "Passed"), ("failed", "Failed")],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_committee_member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="no_confidence_motions",
                        to="governance.committeemember",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "No-confidence Motion",
                "verbose_name_plural": "No-confidence Motions",
                "ordering": ["-filed_date"],
            },
        ),
        migrations.CreateModel(
            name="HandoverRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cash_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("assets_summary", models.TextField(blank=True)),
                ("deadline_date", models.DateField()),
                ("completed_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("completed", "Completed"), ("escalated", "Escalated")],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "incoming_committee_member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="handovers_incoming",
                        to="governance.committeemember",
                    ),
                ),
                (
                    "outgoing_committee_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="handovers_outgoing",
                        to="governance.committeemember",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Handover Record",
                "verbose_name_plural": "Handover Records",
                "ordering": ["-deadline_date"],
            },
        ),
        migrations.CreateModel(
            name="Election",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "election_committee_members",
                    models.TextField(help_text="Names / designations of the election committee members"),
                ),
                ("election_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("in_progress", "In Progress"), ("completed", "Completed")],
                        default="in_progress",
                        max_length=16,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Election",
                "verbose_name_plural": "Elections",
                "ordering": ["-election_date"],
            },
        ),
        migrations.AddField(
            model_name="committeemember",
            name="subcommittees",
            field=models.ManyToManyField(blank=True, related_name="committee_members", to="governance.subcommittee"),
        ),
        migrations.AddField(
            model_name="committeemember",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Candidate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position_applied", models.CharField(max_length=64)),
                ("votes_received", models.PositiveIntegerField(default=0)),
                (
                    "result",
                    models.CharField(
                        choices=[("elected", "Elected"), ("not_elected", "Not Elected")],
                        default="not_elected",
                        max_length=16,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "election",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="candidates", to="governance.election"
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="candidacies", to="members.member"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Candidate",
                "verbose_name_plural": "Candidates",
                "ordering": ["-votes_received"],
            },
        ),
    ]
