# Generated by Django 4.2.30 on 2026-07-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeemember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='committee_members/'),
        ),
    ]
