# Generated by Django 4.2.30 on 2026-07-14 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_household_english_name'),
        ('governance', '0002_committeemember_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidacies', to='members.household'),
        ),
        migrations.AlterField(
            model_name='committeemember',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_roles', to='members.household'),
        ),
    ]
