# Generated by Django 4.2.30 on 2026-09-14 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('governance', '0003_alter_candidate_member_alter_committeemember_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeemember',
            name='content_type',
            field=models.ForeignKey(default=1, limit_choices_to={'model__in': ('household', 'member')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='committeemember',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='committeemember',
            unique_together={('content_type', 'object_id')},
        ),
        migrations.RemoveField(
            model_name='committeemember',
            name='member',
        ),
    ]
