# Generated by Django 4.2.30 on 2026-06-23 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="pdf_file",
            field=models.FileField(blank=True, upload_to="receipts/%Y/%m/"),
        ),
    ]
