# Generated by Django 4.2.30 on 2026-06-29 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_receipt_pdf_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feecollection",
            name="fee_type",
            field=models.CharField(
                choices=[
                    ("membership", "Membership"),
                    ("renewal", "Renewal"),
                    ("royalty", "Royalty"),
                    ("visitor_entry", "Visitor Entry"),
                    ("other", "Other"),
                ],
                max_length=16,
            ),
        ),
    ]
