# Generated by Django 4.2.30 on 2026-08-29 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_feecollection_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feecollection',
            name='fee_type',
            field=models.CharField(choices=[('membership', 'Membership'), ('renewal', 'Renewal'), ('royalty', 'Royalty'), ('visitor_entry', 'Visitor Entry'), ('other', 'Other'), ('penalty', 'Penalty'), ('worm_compost', 'Worm Compost'), ('arrears_collection', 'Arrears Collection'), ('wildgrass', 'Wildgrass'), ('bid_document', 'Bid Document'), ('hall_rent', 'Hall Rent'), ('caned_bamboo', 'Caned Bamboo'), ('forest_products', 'Forest Products'), ('deposit', 'Deposit')], max_length=24),
        ),
    ]
