# Generated by Django 4.2.30 on 2026-09-08 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_alter_feecollection_fee_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='feecollection',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
