# Generated by Django 4.2.30 on 2026-09-08 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_feecollection_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='feecollection',
            name='remarks',
            field=models.TextField(blank=True),
        ),
    ]
