# Generated by Django 4.2.30 on 2026-09-08 01:39

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_feecollection_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='feecollection',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
