# Generated by Django 4.2.30 on 2026-09-08 01:49

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_feecollection_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feecollection',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
