# Generated by Django 4.2.30 on 2026-06-23 01:52

from decimal import Decimal

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import apps.core.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="email address")),
                ("first_name", models.CharField(blank=True, max_length=150, verbose_name="first name")),
                ("last_name", models.CharField(blank=True, max_length=150, verbose_name="last name")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("committee_officer", "Committee Officer"),
                            ("member", "Member"),
                            ("sub_committee_member", "Sub-committee Member"),
                            ("dfo_viewer", "DFO Viewer"),
                            ("admin", "System Administrator"),
                        ],
                        db_index=True,
                        default="member",
                        max_length=24,
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                ("date_joined", models.DateTimeField(default=django.utils.timezone.now, verbose_name="date joined")),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
            managers=[
                ("objects", apps.core.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="ReceiptSequence",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("last_number", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Receipt Sequence",
                "verbose_name_plural": "Receipt Sequence",
            },
        ),
        migrations.CreateModel(
            name="SystemConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("new_household_entry_fee", models.DecimalField(decimal_places=2, default=Decimal("100.00"), max_digits=12)),
                (
                    "split_household_entry_fee",
                    models.DecimalField(decimal_places=2, default=Decimal("50.00"), max_digits=12),
                ),
                ("renewal_fee_on_time", models.DecimalField(decimal_places=2, default=Decimal("50.00"), max_digits=12)),
                ("renewal_fee_overdue_3yr", models.DecimalField(decimal_places=2, default=Decimal("100.00"), max_digits=12)),
                ("renewal_fee_overdue_5yr", models.DecimalField(decimal_places=2, default=Decimal("200.00"), max_digits=12)),
                (
                    "renewal_fee_overdue_5yr_plus",
                    models.DecimalField(decimal_places=2, default=Decimal("300.00"), max_digits=12),
                ),
                ("membership_cancellation_years", models.PositiveSmallIntegerField(default=5)),
                ("forest_dev_min_percent", models.DecimalField(decimal_places=2, default=Decimal("50.00"), max_digits=5)),
                ("poor_targeted_min_percent", models.DecimalField(decimal_places=2, default=Decimal("25.00"), max_digits=5)),
                (
                    "cash_chair_approval_limit",
                    models.DecimalField(decimal_places=2, default=Decimal("5000.00"), max_digits=12),
                ),
                (
                    "cash_treasurer_approval_limit",
                    models.DecimalField(decimal_places=2, default=Decimal("10000.00"), max_digits=12),
                ),
                (
                    "audit_external_threshold",
                    models.DecimalField(decimal_places=2, default=Decimal("50000.00"), max_digits=12),
                ),
                ("informant_reward_percent", models.DecimalField(decimal_places=2, default=Decimal("10.00"), max_digits=5)),
                (
                    "no_confidence_signature_percent",
                    models.DecimalField(decimal_places=2, default=Decimal("25.00"), max_digits=5),
                ),
                ("handover_deadline_days", models.PositiveSmallIntegerField(default=7)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "System Configuration",
                "verbose_name_plural": "System Configuration",
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("tree_count_adjustment", "Tree count adjustment"),
                            ("wealth_class_change", "Wealth classification change"),
                            ("fund_rule_change", "Fund allocation rule change"),
                            ("harvest_approval", "Harvest approval"),
                            ("harvest_rejection", "Harvest rejection"),
                            ("sale_recorded", "Sale recorded"),
                            ("offense_resolved", "Offense resolved"),
                            ("membership_cancellation", "Membership cancellation"),
                            ("manual_override", "Manual override"),
                        ],
                        max_length=32,
                    ),
                ),
                ("model_name", models.CharField(max_length=64)),
                ("object_id", models.CharField(blank=True, max_length=64)),
                ("old_value", models.TextField(blank=True)),
                ("new_value", models.TextField(blank=True)),
                ("reason", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
