# Generated by Django 4.2.30 on 2026-06-23 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemconfig",
            name="current_fiscal_year",
            field=models.CharField(default="2082/83", max_length=16),
        ),
    ]
