# Generated by Django 4.2.30 on 2026-06-23 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_systemconfig_current_fiscal_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemconfig",
            name="min_dalit_or_minority_committee_members",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="min_female_committee_members",
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
