# Generated by Django 4.2.30 on 2026-09-10 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_systemconfig_min_dalit_or_minority_committee_members_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemconfig',
            name='current_fiscal_year',
            field=models.CharField(default='2026/27', max_length=16),
        ),
    ]
