# Generated by Django 4.2.30 on 2026-09-11 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_systemconfig_current_fiscal_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('committee_chair', 'Committee Chair'), ('member', 'Member'), ('sub_committee_member', 'Sub-committee Member'), ('dfo_viewer', 'DFO Viewer'), ('admin', 'System Administrator'), ('staff', 'Staff'), ('secretary', 'Secretary')], db_index=True, default='member', max_length=24),
        ),
    ]
