# Generated by Django 4.2.30 on 2026-09-12 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('cash_approval', 'Cash Transaction Approval Request'), ('bank_approval', 'Bank Transaction Approval Request'), ('budget_approval', 'Budget Allocation Approval Request'), ('harvest_approval', 'Harvest Approval Request'), ('member_request', 'Member Request'), ('system_alert', 'System Alert'), ('offense_report', 'Offense Report'), ('election_notice', 'Election Notice')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('unread', 'Unread'), ('read', 'Read'), ('actioned', 'Actioned')], default='unread', max_length=16)),
                ('content_type', models.CharField(blank=True, help_text="Model name (e.g., 'CashTransaction')", max_length=64)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('action_required', models.BooleanField(default=False)),
                ('action_deadline', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('actioned_at', models.DateTimeField(blank=True, null=True)),
                ('action_notes', models.TextField(blank=True)),
                ('actioned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actioned_notifications', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(help_text='User receiving the notification (typically chair)', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'status'], name='core_notifi_recipie_1989cb_idx'), models.Index(fields=['recipient', 'notification_type'], name='core_notifi_recipie_63521d_idx')],
            },
        ),
    ]
