# Generated by Django 4.2.30 on 2026-09-14 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('cash_approval', 'Cash Transaction Approval Request'), ('bank_approval', 'Bank Transaction Approval Request'), ('budget_approval', 'Budget Allocation Approval Request'), ('harvest_approval', 'Harvest Approval Request'), ('member_request', 'Member Request'), ('system_alert', 'System Alert'), ('offense_report', 'Offense Report'), ('election_notice', 'Election Notice'), ('cheque', 'Cheque Payment Notification'), ('digital_wallet', 'Digital Wallet Payment Notification')], max_length=32),
        ),
    ]
