# Generated by Django 4.2.30 on 2026-07-14 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_household_english_name'),
        ('harvest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvestrequest',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='harvest_requests', to='members.household'),
        ),
    ]
