# Generated by Django 4.2.30 on 2026-07-05 06:26

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='rate_applied',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Auto-filled from price rate; editable by committee with audit note', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
