# Generated by Django 4.2.30 on 2026-07-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_sale_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='buyer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
