# Generated by Django 4.2.30 on 2026-07-14 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forest', '0010_remove_treecountregister_forest_tree_operati_baf15c_idx_and_more'),
        ('inventory', '0004_alter_sale_buyer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimberLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree_no', models.CharField(help_text='रुख नं.', max_length=20, verbose_name='Tree No.')),
                ('tree_golia_no', models.CharField(blank=True, help_text='रुखको गोलिया नं.', max_length=20, verbose_name="Tree's Log No.")),
                ('golia_no', models.CharField(help_text='गोलिया नं.', max_length=20, verbose_name='Log (Golia) No.')),
                ('girth_inch', models.FloatField(blank=True, help_text='गोलाई (घेरा), इन्चमा', null=True, verbose_name='Girth (inch)')),
                ('length_feet', models.FloatField(blank=True, help_text='लम्बाई, फिटमा', null=True, verbose_name='Length (ft)')),
                ('volume_cubic_feet', models.FloatField(blank=True, help_text='आयतन (घन फिट)', null=True, verbose_name='Volume (cu.ft)')),
                ('total_pieces', models.PositiveIntegerField(default=0, help_text='ढेड्रो टुक्रा जम्मा', verbose_name='Total Pieces')),
                ('timber1_pieces', models.PositiveIntegerField(default=0, help_text='टिम्बर नं. १ - व्यास नं. १ को टुक्रा', verbose_name='Timber No.1 - Pieces')),
                ('timber1_diameter_1_inch', models.FloatField(blank=True, null=True, verbose_name='Timber No.1 - Diameter 1 (inch)')),
                ('timber1_diameter_2_inch', models.FloatField(blank=True, null=True, verbose_name='Timber No.1 - Diameter 2 (inch)')),
                ('timber2_pieces', models.PositiveIntegerField(default=0, help_text='टिम्बर नं. २ - व्यास नं. १ को टुक्रा', verbose_name='Timber No.2 - Pieces')),
                ('timber2_diameter_1_inch', models.FloatField(blank=True, null=True, verbose_name='Timber No.2 - Diameter 1 (inch)')),
                ('timber2_diameter_2_inch', models.FloatField(blank=True, null=True, verbose_name='Timber No.2 - Diameter 2 (inch)')),
                ('avg_diameter_length_1_feet', models.FloatField(blank=True, help_text='औसत व्यासको लम्बाई (फि.)', null=True, verbose_name='Avg. Diameter Length 1 (ft)')),
                ('avg_diameter_length_2_feet', models.FloatField(blank=True, help_text='औसत व्यासको लम्बाई (फि.)', null=True, verbose_name='Avg. Diameter Length 2 (ft)')),
                ('sawn_volume_cft', models.FloatField(blank=True, help_text='चिरिएको काठको आयतन (Volume, Cft)', null=True, verbose_name='Sawn Volume (Cft)')),
                ('wastage_percent', models.FloatField(blank=True, help_text='ढेड्रोको प्रतिशत (waste percentage)', null=True, verbose_name='Wastage (%)')),
                ('net_volume_cft', models.FloatField(blank=True, help_text='नेट आयतन (क्यु.फि.)', null=True, verbose_name='Net Volume (Cft)')),
                ('grade', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], help_text='गोलियाको ग्रेड (A / B / C)', max_length=5, verbose_name='Log Grade')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timber_log_entries', to='forest.species')),
            ],
            options={
                'verbose_name': 'Timber Log Entry',
                'verbose_name_plural': 'Timber Log Entries',
                'indexes': [models.Index(fields=['golia_no'], name='inventory_t_golia_n_6233be_idx')],
            },
        ),
    ]
