# Generated by Django 4.2.30 on 2026-09-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_timberlogentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricerate',
            name='grade',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=16),
        ),
        migrations.AlterField(
            model_name='sale',
            name='grade',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=16),
        ),
        migrations.AlterField(
            model_name='timberlogentry',
            name='grade',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], help_text='गोलियाको ग्रेड (A / B / C)', max_length=5, verbose_name='Log Grade'),
        ),
    ]
