# Generated by Django 4.2.30 on 2026-09-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_pricerate_grade_alter_sale_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockledger',
            name='grade',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=16),
        ),
    ]
