# Generated by Django 4.2.30 on 2026-07-01 14:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forest', '0006_wildlifespecies'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeSurveyForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form_number', models.CharField(help_text='Form identification number (पूर्जी क्र.स.)', max_length=50, unique=True)),
                ('survey_date', models.DateField(help_text='Date of survey (मिति)')),
                ('district', models.CharField(help_text='जिल्ला', max_length=255)),
                ('municipality', models.CharField(help_text='गाउँपालिका / नगरपालिका', max_length=255)),
                ('ward_number', models.PositiveIntegerField(help_text='वार्ड नं.')),
                ('plot_number', models.PositiveIntegerField(help_text='प्लट नं.')),
                ('forest_category', models.CharField(help_text='वन कक्षा', max_length=50)),
                ('community_representative', models.CharField(blank=True, help_text='समुदायिक बन उपभोक्ता प्रतिनिधि (नाम)', max_length=255)),
                ('community_representative_sign_date', models.DateField(blank=True, help_text='समुदायिक बन उपभोक्ता प्रतिनिधि दस्तखत (मिति)', null=True)),
                ('forest_officer', models.CharField(blank=True, help_text='वन प्रतिनिधि (नाम)', max_length=255)),
                ('forest_officer_sign_date', models.DateField(blank=True, help_text='वन प्रतिनिधि दस्तखत (मिति)', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional remarks')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='survey_forms', to='forest.forestblock')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('operational_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='survey_forms', to='forest.operationalplan')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tree Survey Form',
                'verbose_name_plural': 'Tree Survey Forms',
                'ordering': ['-survey_date', 'block'],
            },
        ),
        migrations.CreateModel(
            name='TreeSurveyFormItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('serial_number', models.PositiveIntegerField(help_text='क्र.स.')),
                ('girth_cm', models.DecimalField(decimal_places=1, help_text='गोलाई न. (Girth in cm)', max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('height_m', models.DecimalField(decimal_places=1, help_text='लाइड (Height in m)', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('volume_cubic_m', models.DecimalField(decimal_places=3, help_text='आयतन (Volume in cubic meter)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('fuelwood_volume_cubic_m', models.DecimalField(decimal_places=3, default=0, help_text='छोटिकरन (Fuelwood volume)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('wood_type', models.CharField(choices=[('timber', 'काठ'), ('fuelwood', 'दाउरा'), ('other', 'अन्य')], help_text='इस्पात निकासको किसिम (Wood type)', max_length=50)),
                ('remarks', models.TextField(blank=True, help_text='टिप्पणी')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('species', models.ForeignKey(help_text='खान्चको नाम (Species name)', on_delete=django.db.models.deletion.PROTECT, to='forest.species')),
                ('survey_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tree_items', to='forms.treesurveyform')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tree Survey Form Item',
                'verbose_name_plural': 'Tree Survey Form Items',
                'ordering': ['survey_form', 'serial_number'],
                'unique_together': {('survey_form', 'serial_number')},
            },
        ),
    ]
