# Generated by Django 4.2.30 on 2026-07-02 14:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forest', '0008_alter_forestblock_block_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuttingRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form_number', models.CharField(help_text='Form identification number (पूर्जी क्र.स.)', max_length=50, unique=True)),
                ('register_date', models.DateField(help_text='Date of register (मिति)')),
                ('zone', models.CharField(help_text='क्षेत्र (Zone)', max_length=255)),
                ('district', models.CharField(help_text='जिल्ला (District)', max_length=255)),
                ('municipality', models.CharField(help_text='गाउँपालिका / नगरपालिका', max_length=255)),
                ('ward_number', models.PositiveIntegerField(help_text='वार्ड नं.')),
                ('forest_classification', models.CharField(blank=True, help_text='वन-क्षिजिञयात (Forest Classification)', max_length=255)),
                ('block_plot_name', models.CharField(help_text='खण्ड/प्लटको नाम (Block/Plot name)', max_length=255)),
                ('block_plot_type', models.CharField(blank=True, help_text='खण्ड/प्लटको किसिम (Type)', max_length=255)),
                ('cutting_location', models.CharField(help_text='घाटागीरोको स्थान (Cutting location)', max_length=255)),
                ('community_representative_name', models.CharField(blank=True, help_text='सामुदायिक वनको प्रतिनिधि नाम (Name)', max_length=255)),
                ('community_representative_position', models.CharField(blank=True, help_text='सामुदायिक वनको प्रतिनिधि पद (Position)', max_length=255)),
                ('community_representative_sign_date', models.DateField(blank=True, help_text='सामुदायिक वनको प्रतिनिधि दस्तखत मिति (Date)', null=True)),
                ('forest_officer_name', models.CharField(blank=True, help_text='वन प्रतिनिधि नाम (Name)', max_length=255)),
                ('forest_officer_position', models.CharField(blank=True, help_text='वन प्रतिनिधि पद (Position)', max_length=255)),
                ('forest_officer_sign_date', models.DateField(blank=True, help_text='वन प्रतिनिधि दस्तखत मिति (Date)', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional remarks')),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cutting_registers', to='forest.forestblock')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('operational_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cutting_registers', to='forest.operationalplan')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cutting Register',
                'verbose_name_plural': 'Cutting Registers',
                'ordering': ['-register_date', 'block'],
            },
        ),
        migrations.AlterField(
            model_name='treesurveyform',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='survey_forms', to='forest.forestblock'),
        ),
        migrations.CreateModel(
            name='CuttingRegisterItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('serial_number', models.PositiveIntegerField(help_text='मिमिट (Serial number)')),
                ('entry_time', models.TimeField(blank=True, help_text='समय (Time)', null=True)),
                ('plot_number', models.CharField(help_text='रमाना न. (Plot number)', max_length=50)),
                ('quota_number', models.CharField(blank=True, help_text='गोपिया न. (Quota/License number)', max_length=50)),
                ('size_measurement', models.CharField(help_text='नाप साइज (Size/Measurement)', max_length=255)),
                ('volume_cubic_m', models.DecimalField(decimal_places=3, help_text='आयतन (Volume in cubic meter)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('comments', models.CharField(blank=True, help_text='दादुरा (Comments)', max_length=500)),
                ('remarks', models.TextField(blank=True, help_text='कैफियत (Remarks)')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('cutting_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cutting_items', to='forms.cuttingregister')),
                ('species', models.ForeignKey(help_text='जात (Species name)', on_delete=django.db.models.deletion.PROTECT, to='forest.species')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cutting Register Item',
                'verbose_name_plural': 'Cutting Register Items',
                'ordering': ['cutting_register', 'serial_number'],
                'unique_together': {('cutting_register', 'serial_number')},
            },
        ),
    ]
