# Generated by Django 4.2.30 on 2026-07-05 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forest', '0009_forestboundary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0002_cuttingregister_alter_treesurveyform_block_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FellingRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.CharField(blank=True, max_length=255, verbose_name='Area (क्षेत्र)')),
                ('district', models.CharField(blank=True, max_length=255, verbose_name='District (जिल्ला)')),
                ('sub_division', models.CharField(blank=True, max_length=255, verbose_name='Sub-division (सब-डिभिजन)')),
                ('block_name_and_type', models.CharField(blank=True, max_length=255, verbose_name='Block/Plot name & type (खण्ड/प्लटको नाम र किसिम)')),
                ('felling_location', models.CharField(blank=True, max_length=255, verbose_name='Felling location (घाटगद्दीको स्थान)')),
                ('cutting_agency_name', models.CharField(blank=True, max_length=255, verbose_name='Cutting agency name (कटान गर्ने निकायको नाम)')),
                ('tree_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tree count (रुख संख्या)')),
                ('felling_sawing_deadline', models.DateField(blank=True, null=True, verbose_name='Felling/sawing deadline (कटान चिरान म्याद)')),
                ('dispatch_deadline', models.DateField(blank=True, null=True, verbose_name='Dispatch deadline (निकासी म्याद)')),
                ('cfug_rep_name', models.CharField(blank=True, max_length=255, verbose_name='CFUG rep. name (नाम)')),
                ('cfug_rep_position', models.CharField(blank=True, max_length=255, verbose_name='CFUG rep. position (पद)')),
                ('cfug_rep_signed_date', models.DateField(blank=True, null=True, verbose_name='CFUG rep. signed date (मिति)')),
                ('forest_rep_name', models.CharField(blank=True, max_length=255, verbose_name='Forest rep. name (नाम)')),
                ('forest_rep_position', models.CharField(blank=True, max_length=255, verbose_name='Forest rep. position (पद)')),
                ('forest_rep_signed_date', models.DateField(blank=True, null=True, verbose_name='Forest rep. signed date (मिति)')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Felling Register (Anusuchi-8)',
                'verbose_name_plural': 'Felling Registers (Anusuchi-8)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FellingRegisterEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_date', models.DateField(blank=True, null=True, verbose_name='Date (मिति)')),
                ('entry_time', models.TimeField(blank=True, null=True, verbose_name='Time (समय)')),
                ('rawana_number', models.CharField(blank=True, max_length=100, verbose_name='Rawana / transit permit no. (रमाना नं.)')),
                ('golia_number', models.CharField(blank=True, max_length=100, verbose_name='Log / golia no. (गोलिया नं.)')),
                ('measurement_size', models.CharField(blank=True, max_length=255, verbose_name='Measurement / size (नाप साइज)')),
                ('volume_cubic_feet', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Volume in cu.ft. (आयतन क्यू.फि.)')),
                ('firewood_chatta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Firewood in chatta (दाउरा चट्टा)')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarks (कैफियत)')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='forms.fellingregister')),
                ('species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='felling_register_entries', to='forest.species')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Felling Register Entry',
                'verbose_name_plural': 'Felling Register Entries',
                'ordering': ['entry_date', 'entry_time', 'id'],
            },
        ),
    ]
