# Generated by Django 4.2.30 on 2026-07-06 05:34

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_sale_rate_applied'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0003_fellingregister_fellingregisterentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForestProductReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt_no', models.CharField(max_length=64, unique=True)),
                ('cfug_registration_no', models.CharField(blank=True, help_text='उपभोक्ता समूहको दर्ता नं.', max_length=64)),
                ('buyer_name', models.CharField(help_text="श्री — recipient's full name", max_length=255)),
                ('buyer_address', models.CharField(blank=True, max_length=255)),
                ('issue_date', models.DateField()),
                ('receiver_name', models.CharField(blank=True, max_length=255)),
                ('receiver_date', models.DateField(blank=True, null=True)),
                ('issuer_name', models.CharField(blank=True, max_length=255)),
                ('issuer_position', models.CharField(blank=True, max_length=128)),
                ('issuer_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('sales', models.ManyToManyField(blank=True, related_name='product_receipts', to='inventory.sale')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Forest Product Receipt',
                'verbose_name_plural': 'Forest Product Receipts',
                'ordering': ['-issue_date', '-receipt_no'],
            },
        ),
        migrations.CreateModel(
            name='ForestProductReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_name', models.CharField(max_length=255)),
                ('grade', models.CharField(blank=True, max_length=64)),
                ('unit', models.CharField(max_length=32)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('rate_per_unit', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('remarks', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='forms.forestproductreceipt')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Receipt Item',
                'verbose_name_plural': 'Receipt Items',
                'ordering': ['id'],
            },
        ),
    ]
