# Generated by Django 4.2.30 on 2026-06-23 02:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ForestBlock",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("block_name", models.CharField(max_length=255)),
                (
                    "area_hectares",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
            ],
            options={
                "verbose_name": "Forest Block",
                "verbose_name_plural": "Forest Blocks",
                "ordering": ["block_name"],
            },
        ),
        migrations.CreateModel(
            name="OperationalPlan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField()),
                (
                    "approved_harvest_limit",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Operational Plan",
                "verbose_name_plural": "Operational Plans",
                "ordering": ["-valid_from"],
            },
        ),
        migrations.CreateModel(
            name="Species",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("species_name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Species",
                "verbose_name_plural": "Species",
                "ordering": ["species_name"],
            },
        ),
        migrations.CreateModel(
            name="TreeCountRegister",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "total_count",
                    models.PositiveIntegerField(
                        help_text="Baseline tree count from inventory",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("harvested_count", models.PositiveIntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "adjustment_reason",
                    models.TextField(blank=True, help_text="Reason for any manual adjustment to the baseline total_count"),
                ),
                (
                    "block",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tree_counts",
                        to="forest.forestblock",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "species",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="tree_counts", to="forest.species"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tree Count Register",
                "verbose_name_plural": "Tree Count Register",
                "ordering": ["species__species_name", "block__block_name"],
            },
        ),
        migrations.CreateModel(
            name="TreeCountHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "change_amount",
                    models.IntegerField(
                        help_text="Number of trees harvested in this change",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("change_date", models.DateField()),
                ("note", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="history", to="forest.treecountregister"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tree Count History",
                "verbose_name_plural": "Tree Count History",
                "ordering": ["-change_date"],
            },
        ),
    ]
