# Generated by Django 4.2.30 on 2026-06-30 16:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('harvest', '0001_initial'),
        ('forest', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HarvestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('harvest_date', models.DateField()),
                ('harvest_quantity_cubic_m', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Harvest Log',
                'verbose_name_plural': 'Harvest Logs',
                'ordering': ['-harvest_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='treecountregister',
            options={'ordering': ['block__block_name', 'section_number', 'plot_number', 'tree_number'], 'verbose_name': 'Tree Count Register', 'verbose_name_plural': 'Tree Count Register'},
        ),
        migrations.RemoveConstraint(
            model_name='treecountregister',
            name='unique_species_block_tree_count',
        ),
        migrations.AddField(
            model_name='species',
            name='local_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='species',
            name='scientific_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='treecountregister',
            name='basal_area_sqm',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Basal area in sq meters (बेसल एरिआ वगा मि.)', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='treecountregister',
            name='branch_volume_cubic_m',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Branch volume in cubic meters (हाँगाको आयतन)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='treecountregister',
            name='fuelwood_volume_cubic_m',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Fuelwood volume in cubic meters (दाउरा जम्मा आयतन घ.मि.)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='treecountregister',
            name='girth_cm',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Girth at breast height in cm (गोलाई)', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='treecountregister',
            name='gross_volume_cubic_m',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Gross volume in cubic meters (ग्रस आयतन)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='treecountregister',
            name='height_m',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Tree height in meters (उचाई)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='treecountregister',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this record is active or archived'),
        ),
        migrations.AddField(
            model_name='treecountregister',
            name='is_harvestable',
            field=models.BooleanField(default=True, help_text='Whether this tree can be harvested'),
        ),
        migrations.AddField(
            model_name='treecountregister',
            name='net_volume_cubic_m',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Net volume in cubic meters (नेट आयतन घ.मि.)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='treecountregister',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes for this tree record'),
        ),
        migrations.AddField(
            model_name='treecountregister',
            name='operational_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tree_registers', to='forest.operationalplan'),
        ),
        migrations.AddField(
            model_name='treecountregister',
            name='plot_number',
            field=models.PositiveIntegerField(blank=True, help_text='Plot number (प्लट नं)', null=True),
        ),
        migrations.AddField(
            model_name='treecountregister',
            name='r_factor',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='R factor for branch volume calculation', max_digits=4),
        ),
        migrations.AddField(
            model_name='treecountregister',
            name='r_less_than_10',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='R factor for <10cm diameter', max_digits=4),
        ),
        migrations.AddField(
            model_name='treecountregister',
            name='section_number',
            field=models.PositiveIntegerField(default=1, help_text='Section/block number (खण्ड नं)'),
        ),
        migrations.AddField(
            model_name='treecountregister',
            name='stem_volume_cubic_m',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Stem volume in cubic meters (काण्डको आयतन)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='treecountregister',
            name='survey_date',
            field=models.DateField(blank=True, help_text='Date of survey/measurement', null=True),
        ),
        migrations.AddField(
            model_name='treecountregister',
            name='total_volume_cubic_m',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Total tree volume in cubic meters (रुखको आयतन)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='treecountregister',
            name='tree_class',
            field=models.CharField(blank=True, choices=[('i', 'I'), ('ii', 'II'), ('iii', 'III')], help_text='Tree class/category (श्रेणी)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='treecountregister',
            name='tree_number',
            field=models.PositiveIntegerField(blank=True, help_text='Tree sequence number in plot (क्र.स.)', null=True),
        ),
        migrations.AddField(
            model_name='treecountregister',
            name='volume_less_than_10_cubic_m',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Volume for <10cm diameter', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='treecountregister',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tree_registers', to='forest.forestblock'),
        ),
        migrations.AlterField(
            model_name='treecountregister',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tree_registers', to='forest.species'),
        ),
        migrations.AlterUniqueTogether(
            name='treecountregister',
            unique_together={('block', 'operational_plan', 'species', 'tree_number'), ('block', 'section_number', 'plot_number', 'tree_number')},
        ),
        migrations.AddIndex(
            model_name='treecountregister',
            index=models.Index(fields=['block', 'section_number', 'plot_number'], name='forest_tree_block_i_081805_idx'),
        ),
        migrations.AddIndex(
            model_name='treecountregister',
            index=models.Index(fields=['species'], name='forest_tree_species_7ecac8_idx'),
        ),
        migrations.AddIndex(
            model_name='treecountregister',
            index=models.Index(fields=['operational_plan'], name='forest_tree_operati_baf15c_idx'),
        ),
        migrations.AddField(
            model_name='harvestlog',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='harvestlog',
            name='reference_harvest_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='harvest_logs', to='harvest.harvestrequest'),
        ),
        migrations.AddField(
            model_name='harvestlog',
            name='tree_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='harvest_logs', to='forest.treecountregister'),
        ),
        migrations.AddField(
            model_name='harvestlog',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='treecountregister',
            name='adjustment_reason',
        ),
        migrations.RemoveField(
            model_name='treecountregister',
            name='harvested_count',
        ),
        migrations.RemoveField(
            model_name='treecountregister',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='treecountregister',
            name='total_count',
        ),
    ]
