# Generated by Django 4.2.30 on 2026-06-30 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forest', '0003_harvestlog_alter_treecountregister_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimberCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wood_volume', models.DecimalField(decimal_places=2, help_text='घन फिट', max_digits=12)),
                ('firewood', models.DecimalField(decimal_places=2, help_text='चट्टा', max_digits=10)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='forest.forestblock')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='forest.species')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['block', 'species'],
                'unique_together': {('block', 'species')},
            },
        ),
    ]
