# Generated by Django 4.2.30 on 2026-06-30 16:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forest', '0004_timbercollection'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoleCountRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plot_number', models.PositiveIntegerField(blank=True, help_text='Plot number (प्लट नं)', null=True)),
                ('tree_number', models.PositiveIntegerField(blank=True, help_text='Tree sequence number in plot (क्र.स.)', null=True)),
                ('girth_cm', models.DecimalField(blank=True, decimal_places=1, help_text='Girth at breast height in cm (गोलाई)', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('height_m', models.DecimalField(blank=True, decimal_places=1, help_text='Tree height in meters (उचाई)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('tree_class', models.CharField(blank=True, choices=[('i', 'I'), ('ii', 'II'), ('iii', 'III')], help_text='Tree class/category (श्रेणी)', max_length=10, null=True)),
                ('basal_area_sqm', models.DecimalField(blank=True, decimal_places=4, help_text='Basal area in sq meters (बेसल एरिआ वगा मि.)', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('stem_volume_cubic_m', models.DecimalField(blank=True, decimal_places=3, help_text='Stem volume in cubic meters (काण्डको आयतन)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('r_factor', models.DecimalField(decimal_places=2, default=0.0, help_text='R factor for branch volume calculation', max_digits=4)),
                ('branch_volume_cubic_m', models.DecimalField(blank=True, decimal_places=3, help_text='Branch volume in cubic meters (हाँगाको आयतन)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_volume_cubic_m', models.DecimalField(blank=True, decimal_places=3, help_text='Total tree volume in cubic meters (रुखको आयतन)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('r_less_than_10', models.DecimalField(decimal_places=2, default=0.0, help_text='R factor for <10cm diameter', max_digits=4)),
                ('volume_less_than_10_cubic_m', models.DecimalField(blank=True, decimal_places=3, help_text='Volume for <10cm diameter', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('gross_volume_cubic_m', models.DecimalField(blank=True, decimal_places=3, help_text='Gross volume in cubic meters (ग्रस आयतन)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('net_volume_cubic_m', models.DecimalField(blank=True, decimal_places=3, help_text='Net volume in cubic meters (नेट आयतन घ.मि.)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('fuelwood_volume_cubic_m', models.DecimalField(blank=True, decimal_places=3, help_text='Fuelwood volume in cubic meters (दाउरा जम्मा आयतन घ.मि.)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('survey_date', models.DateField(blank=True, help_text='Date of survey/measurement', null=True)),
                ('is_harvestable', models.BooleanField(default=True, help_text='Whether this tree can be harvested')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this record is active or archived')),
                ('notes', models.TextField(blank=True, help_text='Additional notes for this tree record')),
            ],
            options={
                'verbose_name': 'Tree Count Register',
                'verbose_name_plural': 'Tree Count Register',
                'ordering': ['block__block_name', 'plot_number', 'tree_number'],
            },
        ),
        migrations.AlterModelOptions(
            name='treecountregister',
            options={'ordering': ['block__block_name', 'plot_number', 'tree_number'], 'verbose_name': 'Tree Count Register', 'verbose_name_plural': 'Tree Count Register'},
        ),
        migrations.RemoveIndex(
            model_name='treecountregister',
            name='forest_tree_block_i_081805_idx',
        ),
        migrations.AlterUniqueTogether(
            name='treecountregister',
            unique_together={('block', 'plot_number', 'tree_number'), ('block', 'operational_plan', 'species', 'tree_number')},
        ),
        migrations.AddIndex(
            model_name='treecountregister',
            index=models.Index(fields=['block', 'plot_number'], name='forest_tree_block_i_406cc3_idx'),
        ),
        migrations.AddField(
            model_name='polecountregister',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pole_registers', to='forest.forestblock'),
        ),
        migrations.AddField(
            model_name='polecountregister',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='polecountregister',
            name='operational_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pole_registers', to='forest.operationalplan'),
        ),
        migrations.AddField(
            model_name='polecountregister',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pole_registers', to='forest.species'),
        ),
        migrations.AddField(
            model_name='polecountregister',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='treecountregister',
            name='section_number',
        ),
        migrations.AddIndex(
            model_name='polecountregister',
            index=models.Index(fields=['block', 'plot_number'], name='forest_pole_block_i_bc08f9_idx'),
        ),
        migrations.AddIndex(
            model_name='polecountregister',
            index=models.Index(fields=['species'], name='forest_pole_species_8d666b_idx'),
        ),
        migrations.AddIndex(
            model_name='polecountregister',
            index=models.Index(fields=['operational_plan'], name='forest_pole_operati_ad8c17_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='polecountregister',
            unique_together={('block', 'plot_number', 'tree_number'), ('block', 'operational_plan', 'species', 'tree_number')},
        ),
    ]
