# Generated by Django 4.2.30 on 2026-07-02 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forest', '0002_forestblock_fields'),
        ('forest', '0006_wildlifespecies'),
    ]

    operations = [
    ]
