# Generated by Django 4.2.30 on 2026-07-02 14:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forest', '0007_merge_0002_forestblock_fields_0006_wildlifespecies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forestblock',
            name='block_name',
            field=models.CharField(help_text='Block name (नाम)', max_length=255, verbose_name='Block name (नाम)'),
        ),
        migrations.AlterField(
            model_name='forestblock',
            name='block_no',
            field=models.PositiveIntegerField(default=1, help_text='Block number', unique=True, verbose_name='Block number (ब्लक नं.)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='forestblock',
            name='canopy_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Canopy coverage percentage (छत्र आच्छादन प्रतिशत)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Canopy coverage percentage (छत्र आच्छादन प्रतिशत)'),
        ),
        migrations.AlterField(
            model_name='forestblock',
            name='forest_condition',
            field=models.CharField(blank=True, help_text='Forest condition (वन अवस्था)', max_length=100, verbose_name='Forest condition (वन अवस्था)'),
        ),
        migrations.AlterField(
            model_name='forestblock',
            name='forest_type',
            field=models.CharField(blank=True, help_text='Forest type (वन प्रकार - प्राकृतिक/रोपित)', max_length=100, verbose_name='Forest type (वन प्रकार - प्राकृतिक/रोपित)'),
        ),
        migrations.AlterField(
            model_name='forestblock',
            name='major_species',
            field=models.JSONField(blank=True, default=list, help_text='Major tree species (प्रमुख वृक्ष प्रजातिहरु)', verbose_name='Major tree species (प्रमुख वृक्ष प्रजातिहरु)'),
        ),
        migrations.AlterField(
            model_name='forestblock',
            name='productive_area_ha',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Productive area in hectares (उत्पादक क्षेत्रफल)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Productive area in hectares (उत्पादक क्षेत्रफल)'),
        ),
        migrations.AlterField(
            model_name='forestblock',
            name='soil_types',
            field=models.JSONField(blank=True, default=list, help_text='Soil types (माटोको प्रकार)', verbose_name='Soil types (माटोको प्रकार)'),
        ),
        migrations.AlterField(
            model_name='forestblock',
            name='title',
            field=models.CharField(blank=True, help_text='Block title/description', max_length=500, verbose_name='Block title/description (शीर्षक/विवरण)'),
        ),
        migrations.AlterField(
            model_name='forestblock',
            name='total_area_ha',
            field=models.DecimalField(decimal_places=2, help_text='Total area in hectares (कुल क्षेत्रफल हेक्टेयरमा)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total area in hectares (कुल क्षेत्रफल हेक्टेयरमा)'),
        ),
    ]
