# Generated by Django 4.2.30 on 2026-07-05 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forest', '0008_alter_forestblock_block_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForestBoundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('boundary_type', models.CharField(choices=[('block', 'Block'), ('zone', 'Zone'), ('buffer', 'Buffer Zone'), ('other', 'Other')], default='block', max_length=16)),
                ('coordinates', models.JSONField(help_text='List of [longitude, latitude] pairs forming the polygon ring')),
                ('description', models.TextField(blank=True)),
                ('source_notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('forest_block', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boundary', to='forest.forestblock')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Forest Boundary',
                'verbose_name_plural': 'Forest Boundaries',
                'ordering': ['name'],
            },
        ),
    ]
