# Generated by Django 4.2.30 on 2026-07-14 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forest', '0009_forestboundary'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='treecountregister',
            name='forest_tree_operati_baf15c_idx',
        ),
        migrations.AlterUniqueTogether(
            name='treecountregister',
            unique_together=set(),
        ),
    ]
