# Generated by Django 4.2.30 on 2026-07-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashtransaction',
            name='cheque_bank_name',
            field=models.CharField(blank=True, help_text='Bank name for cheque payment', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cashtransaction',
            name='cheque_number',
            field=models.CharField(blank=True, help_text='Required if payment type is cheque', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='cashtransaction',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('digital_wallet', 'Digital Wallet')], default='cash', help_text='Payment method used for this transaction', max_length=16),
        ),
    ]
