# Generated by Django 4.2.30 on 2026-07-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0003_banktransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal')], max_length=16, null=True),
        ),
    ]
