# Generated by Django 4.2.30 on 2026-07-14 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0005_budgetallocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetallocation',
            name='approved_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
