# Generated by Django 4.2.30 on 2026-09-12 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fund', '0006_alter_budgetallocation_approved_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashtransaction',
            name='approval_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=16),
        ),
        migrations.AddField(
            model_name='cashtransaction',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashtransaction',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection if rejected'),
        ),
        migrations.AddField(
            model_name='cashtransaction',
            name='submitted_by',
            field=models.ForeignKey(blank=True, help_text='User who submitted for approval (secretary/staff)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_cash_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashtransaction',
            name='submitted_for_approval_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
