# Generated by Django 4.2.30 on 2026-07-14 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_household_english_name'),
        ('offense', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informantreward',
            name='informant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards_received', to='members.household'),
        ),
        migrations.AlterField(
            model_name='offensereport',
            name='informant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informant_rewards', to='members.household'),
        ),
        migrations.AlterField(
            model_name='offensereport',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_offenses', to='members.household'),
        ),
        migrations.AlterField(
            model_name='patrollog',
            name='watcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patrol_logs', to='members.household'),
        ),
    ]
